name: PR Build Check

on:
  pull_request:

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build app (deploy mode)
        run: npm run build -- --mode deploy

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-build
          path: build/
